# Generated by Django 5.2.8 on 2026-02-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_cost_xof",
            new_name="shipping_cost_fcfa",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="tax_amount_xof",
            new_name="tax_amount_fcfa",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_amount_xof",
            new_name="total_amount_fcfa",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="price_xof",
            new_name="price_fcfa",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="total_xof",
            new_name="total_fcfa",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="discount_price_xof",
            new_name="discount_price_fcfa",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price_xof",
            new_name="price_fcfa",
        ),
    ]
