# Generated by Django 5.2.8 on 2026-02-04 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code devise"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                ("symbol", models.CharField(max_length=10, verbose_name="Symbole")),
                ("flag", models.CharField(max_length=10, verbose_name="Emoji drapeau")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Devise par défaut"
                    ),
                ),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="display_stock",
            field=models.BooleanField(
                default=True,
                help_text="Décochez si vous ne voulez PAS montrer le stock au public (ex: produits en précommande, stock caché...)",
                verbose_name="Afficher le stock sur le site ?",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Laisser vide = stock à 0 (rupture de stock)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Stock",
            ),
        ),
        migrations.CreateModel(
            name="UserCurrencyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.currency",
                        verbose_name="Devise préférée",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de devise",
                "verbose_name_plural": "Préférences de devise",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="Taux de change"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_rates",
                        to="core.currency",
                        verbose_name="Devise de base",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rates",
                        to="core.currency",
                        verbose_name="Devise cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux de change",
                "verbose_name_plural": "Taux de change",
                "unique_together": {("base_currency", "target_currency")},
            },
        ),
    ]
