# Generated by Django 5.2.8 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_currency_product_display_stock_alter_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="back_image",
            field=models.ImageField(
                blank=True,
                help_text="Image qui apparaîtra quand l'utilisateur survole l'image principale",
                null=True,
                upload_to="products/backs/",
                verbose_name="Image verso (au survol)",
            ),
        ),
    ]
