# Generated by Django 5.1.15 on 2026-02-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_review_unique_together_alter_review_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["home_position", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="display_on_home",
            field=models.BooleanField(
                default=False, verbose_name="Afficher sur la page d'accueil"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="home_position",
            field=models.IntegerField(
                default=0,
                help_text="Plus le chiffre est bas, plus la catégorie apparaît tôt.",
                verbose_name="Ordre d'affichage",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.category",
                verbose_name="Catégorie parente",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["home_position"], name="core_catego_home_po_ad0b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="core_catego_is_acti_26a709_idx"
            ),
        ),
    ]
