# Generated by Django 5.1.15 on 2026-02-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_category_options_category_display_on_home_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du type"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Identifiant URL (généré automatiquement)",
                        unique=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-box",
                        help_text="Ex: fa-coffee, fa-bread-slice, fa-leaf (sans le préfixe 'fas')",
                        max_length=50,
                        verbose_name="Icône FontAwesome",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description courte"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type de produit",
                "verbose_name_plural": "Types de produits",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="core_produc_product_faebef_idx",
            old_name="core_produc_product_3906a7_idx",
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-coffee", "☕ Café"),
                    ("fa-bread-slice", "🍞 Pain"),
                    ("fa-mug-hot", "☕ Tasse/Machine"),
                    ("fa-blender", "🌪 Mixeur"),
                    ("fa-utensils", "🍴 Accessoires"),
                    ("fa-wine-bottle", "🍷 Boissons"),
                    ("fa-cookie", "🍪 Snacks"),
                    ("fa-leaf", "🌿 Thé/Infusion"),
                    ("fa-box-open", "📦 Général"),
                    ("fa-th-large", "🔲 Tous"),
                ],
                default="fa-box-open",
                help_text="Icône affichée dans la barre de navigation supérieure.",
                max_length=50,
                verbose_name="Icône du filtre",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_filter_main",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, cette catégorie apparaîtra dans la barre de navigation supérieure.",
                verbose_name="Afficher dans la barre de filtres ?",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_on_home",
            field=models.BooleanField(
                default=False,
                help_text="Cochez pour afficher cette catégorie dans la grille d'accueil.",
                verbose_name="Afficher sur la page d'accueil",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["display_on_home"], name="core_catego_display_9bde71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_filter_main"], name="core_catego_is_filt_aadcf2_idx"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.producttype",
                verbose_name="Type de produit",
            ),
        ),
    ]
